server.port=8080
spring.application.name=btg-fondos-api

# Configuracion de AWS
aws.accessKeyId=tu_clave_de_acceso
aws.secretKey=tu_clave_secreta
aws.region=us-east-1

# Nombre de la tabla en DynamoDB
dynamodb.table.name=btg-investment-platform